### ISSUE TITLE
Merge all current feature branches into master after conducting tests

### ISSUE THREAD

**Issue by JohnBehnke** [wtg/RPI_Tours_iOS#29]
All current branches generated over the summer should be merged back into master after we ensure they are all stable.

**Comment by jacobspeicher** [comment]
Only info-screen would need to be merged. location-start is actually implemented in info-screen because of issues with it in its own branch over the summer, skip-steps is broken, and network-check has already been merged, and nothing has changed in it since then. Of course, we should still make sure info-screen is stable.

**Comment by JohnBehnke** [comment]
Do you want to delete the branches that are already merged/stale?

**Comment by jacobspeicher** [comment]
Went through and got rid of stale / merged branches. Only info-screen is left.

**Comment by JohnBehnke** [comment]
Chaaaaaaa
